name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install openssl
          brew install boost
          brew install mongo-cxx-driver
          brew install catch2

      - name: Install vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          .\vcpkg\vcpkg.exe install openssl boost-system boost-beast boost-asio mongo-cxx-driver catch2

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE="${PWD}\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"

      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        run: cmake -S . -B build

      - name: Compile
        run: cmake --build build --config Release