name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install openssl
          brew install boost
          brew install mongo-cxx-driver
          brew install catch2

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install build-essential cmake libssl-dev libsasl2-dev      
          git clone https://github.com/mongodb/mongo-cxx-driver.git --branch releases/stable --depth 1
          cd mongo-cxx-driver/build
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
          sudo cmake --build . --target install


      - name: Build
        run: cmake -S . -B build

      - name: Compile
        run: cmake --build build --config Release